# Generated by Django 3.1.2 on 2021-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('jobs', '0001_initial'), ('jobs', '0002_auto_20200827_1542'), ('jobs', '0003_job_project_url'), ('jobs', '0004_auto_20200827_1556')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=300)),
                ('url', models.URLField(default='www.tanjanyberg.io')),
            ],
        ),
    ]
