# Generated by Django 3.1 on 2020-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200827_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_url',
            field=models.URLField(default='www.tanjanyberg.io'),
            preserve_default=False,
        ),
    ]
