# Generated by Django 3.1 on 2020-08-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='project_url',
            new_name='url',
        ),
    ]
