# Generated by Django 3.1.2 on 2021-06-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210610_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
